### ISSUE TITLE
Migrate to phpcs 3.x

### ISSUE THREAD

**Issue by dmolineus** [phpcq/coding-standard#8]
With phpcs 2.9.0 the last release of the 2.x series was published. We should consider moving to 3.x now.

See https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.9.2 for mor details.

An upgrade guide is here available: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide

**Comment by discordier** [comment]
Yes we should, however, I currently lack the time for rewriting the sniffs.

**Comment by discordier** [comment]
We should really modernize it... I had to fix a bc break in phpcs and could not make the tests work again. :(

**Comment by baumannsven** [comment]
Migrate in 93ad602694ae9c36e206ee9d59703425852bdcb0
